all:
  hosts:
    cisco_router1:
      ansible_host: 192.168.11.11
      ansible_user: XXX
      ansible_password: XXX
      ansible_connection: network_cli
      ansible_network_os: cisco.ios.ios
      # ansible_network_os: ios
    
    # cisco_switch1:
    #   ansible_host: 192.168.11.10
    #   ansible_user: your_username
    #   ansible_password: your_password
    #   ansible_connection: network_cli
    #   ansible_network_os: cisco.ios.ios