---
- name: Configure Cisco IOS Devices from Template
  # hosts: cisco_router1
  hosts: routers
  gather_facts: false

  tasks:

    - name: Print the current hostname
      ansible.builtin.debug:
        msg: "The current inventory is: {{ inventory_hostname }}, hostname: {{ hostname }}"

    - name: Generate a random string with 1 lower, 1 upper, 1 number and 1 special char (at least), length 12
      ansible.builtin.debug:
        var: lookup("community.general.random_string", min_lower=1, min_upper=1, min_special=1, min_numeric=1, length=12)

    - name: Random string display
      ansible.builtin.debug:
        msg: "Random string is: {{ var }}"

    - name: Add Loopback interface
      cisco.ios.ios_config:
        lines:
          - description ANS-TEST-INTERFACE
          - ip address 1.1.1.1 255.255.255.255
        parents: interface Loopback0

    - name: Disable http services
      cisco.ios.ios_config:
        lines:
          - no ip http server
          - no ip http secure-server

    - name: Disable small services
      cisco.ios.ios_config:
        lines:
          - no service tcp-small-servers
          - no service udp-small-servers

    - name: Set hostname
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ hostname }}"
        state: merged

    - name: Add local user
      cisco.ios.ios_config:
        lines:
          - username NEW-{{ hostname }}-OK privilege 15 secret SOMESECRETPASSWORD

    - name: Save running config to startup config (when modified)
      cisco.ios.ios_config:
        save_when: modified
