---
- name: Add network device to ISE
  hosts: all
  gather_facts: false

  tasks:
    - name: Generate a random string with 1 lower, 1 upper, 1 number and 1 special char (at least), length 12
      ansible.builtin.set_fact:
        var_random_string: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, length=12, override_special=special_list) }}"
      vars:
        special_list: "!@#$%^&*()-_+=[]{}:./"

    - name: Check if device already exists in ISE
      ansible.builtin.uri:
        url: "https://10.12.0.98:9060/ers/config/networkdevice?filter=name.EQ.{{ inventory_hostname }}"
        user: "{{ ise_username }}"
        password: "{{ ise_password }}"
        method: GET
        return_content: true
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          User-Agent: Ansible-Playbook
      register: ise_device_status

    - name: Set existence fact
      ansible.builtin.set_fact:
        device_exists: "{{ ise_device_status.json.SearchResult.resources | length > 0 }}"

    - name: Show status if device exists
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} already exists in ISE."
      when: device_exists

    - name: Show status if device does not exist
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} does not exist in ISE."
      when: not device_exists

    - name: Add network device to ISE
      ansible.builtin.uri:
        url: "https://10.12.0.98:9060/ers/config/networkdevice"
        user: "{{ ise_username }}"
        password: "{{ ise_password }}"
        method: POST
        return_content: true
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          User-Agent: ansible-playbook
        body: |
          {
            "NetworkDevice": {
              "name": "{{ inventory_hostname }}",
              "description": "Added via Ansible",
              "NetworkDeviceIPList": [
                {
                  "ipaddress": "{{ ansible_host }}",
                  "mask": 32
                }
              ],
              "tacacsSettings": {
                "sharedSecret": "{{ var_random_string }}",
                "connectModeOptions": "ON_LEGACY"
              }
            }
          }
        status_code: [201, 400]
      register: ise_new_device_response
      when: ise_device_status.status != 200

    - name: ERROR HANDLING
      # ansible.builtin.fail:
      ansible.builtin.debug:
        msg: 
          - "ADD NETWORK DEVICE TO ISE ERROR!"
          - "{{ ise_new_device_response }}"
      # when: ise_new_device_response.status == 400

- name: Add AAA config to device
  hosts: all
  gather_facts: false

  tasks:
    - name: Print variables
      ansible.builtin.debug:  
        msg:
          ISE DEVICE STATUS: "{{ ise_device_status }}"
          SITE_ID: "{{ group_names[0] }}"
          INVENTORY HOSTNAME: "{{ inventory_hostname }}"
          # RANDOM STRING: "{{ hostvars[inventory_hostname].var_random_string }}"
          RANDOM STRING: "{{ var_random_string }}"
          TACACS SOURCE: "{{ tacacs_source | default('Source interface not defined') }}"

    # - name: Create a new user
    #   cisco.ios.ios_user:
    #     name: test_local_user
    #     configured_password: Test123
    #     privilege: 15
    #     password_type: secret
    #     state: present

    # - name: Create a new user
    #   cisco.ios.ios_config:
    #     lines:
    #       - username local_test_user privilege 15 secret Test123

    - name: Add TACACS+
      cisco.ios.ios_config:
        lines:
          - aaa group server tacacs+ AAA_SERVERS
          - server-private 192.168.12.98 key {{ var_random_string }}
          # - ip tacacs source-interface {{ tacacs_source }}

    - name: Add TACACS+ source interface (if defined)
      cisco.ios.ios_config: ip tacacs source-interface {{ tacacs_source }}
      when: tacacs_source is defined

    - name: Add AAA
      cisco.ios.ios_config:
        lines:
          - aaa new-model
          # - aaa authentication login default local
          # - aaa authorization exec default local
          - aaa authorization console
          - aaa authentication login AAA_LIST group AAA_SERVERS local
          - aaa authorization exec AAA_LIST group AAA_SERVERS local 
          - aaa authorization commands 15 AAA_LIST group AAA_SERVERS local

    - name: Configure VTY lines
      cisco.ios.ios_config:
        lines:
          - transport input ssh
          - authorization commands 15 AAA_LIST
          - authorization exec AAA_LIST
          - login authentication AAA_LIST
          # - exec-timeout 30 0
          # - access-class VTY_ACCESS in
        parents: line vty 0 4

    - name: Save running config to startup config (when modified)
      cisco.ios.ios_config:
        save_when: modified


# TODO
# - do not add device if it already exists in ISE
# - do not add username if it already exists on device