---
- hosts: ise_servers
  gather_facts: no

  tasks:
    - name: Add Network Device to ISE
      cisco.ise.network_device:
        # ise_hostname: "{{ ise_hostname }}"
        # ise_username: "{{ ise_username }}"
        # ise_password: "{{ ise_password }}"
        ise_hostname: "192.168.12.98"
        ise_username: "ersadmin"
        ise_password: "Cisco123"
        ise_verify: False
        ise_debug: True
        state: present
        name: "Switch-01"
        description: "Added via Ansible"
        NetworkDeviceIPList:
          - ipaddress: "192.168.10.5"
            mask: 32
        NetworkDeviceGroupList:
          - "Location#All Locations"
          - "Device Type#All Device Types"
        authenticationSettings:
          radiusSharedSecret: "YourSecureRadiusSecret123"
