- name: Basic API call
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Call local Cisco ISE API
      ansible.builtin.uri:
        # url: "https://api.github.com/repos/ansible/ansible"
        url: "https://10.12.0.98:9060/ers/config/networkdevice"
        user: "{{ ise_api_user }}"
        password: "{{ ise_api_pass }}"
        method: GET
        return_content: true
        validate_certs: no
        headers:
          Accept: application/json
          User-Agent: Ansible-Playbook
      register: ise_response

    - name: Show response status
      ansible.builtin.debug:
        msg: "Status: {{ ise_response.status }}, Content-Type: {{ ise_response.content_type }}"

    - name: Access parsed JSON data
      ansible.builtin.debug:
        msg:
          name: "{{ ise_response.json.full_name }}"
          stars: "{{ ise_response.json.stargazers_count }}"
          language: "{{ ise_response.json.language }}"