- name: Basic API call
  hosts: localhost
  gather_facts: false

  tasks:
    - name: ISE devices GET request
      ansible.builtin.uri:
        url: "https://10.12.0.98:9060/ers/config/networkdevice"
        user: "ersadmin"
        password: "Cisco123"
        method: GET
        return_content: true
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          User-Agent: Ansible-Playbook
      register: ise_devices_response

    - name: ISE specific device GET request
      ansible.builtin.uri:
        url: "https://10.12.0.98:9060/ers/config/networkdevice/name/RT2_IOSv"
        user: "ersadmin"
        password: "Cisco123"
        method: GET
        return_content: true
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          User-Agent: Ansible-Playbook
      register: ise_device_response

    - name: Add network device to ISE
      ansible.builtin.uri:
        url: "https://10.12.0.98:9060/ers/config/networkdevice"
        user: "ersadmin"
        password: "Cisco123"
        method: POST
        return_content: true
        validate_certs: no
        headers:
          Accept: application/json
          Content-Type: application/json
          User-Agent: Ansible-Playbook
        body: |
          {
            "NetworkDevice": {
              "name": "RT1_IOSv",
              "description": "Added via Ansible",
              "NetworkDeviceIPList": [
                {
                  "ipaddress": "192.168.12.11",
                  "mask": 32
                }
              ],
              "tacacsSettings": {
                "sharedSecret": "cisco123",
                "connectModeOptions": "ON_LEGACY"
              }
            }
          }
        status_code: [200, 201]
      register: ise_new_device_response

    - name: Show response status
      ansible.builtin.debug:
        msg: 
          General response status: "{{ ise_devices_response.status }}"
          Specific device response status: "{{ ise_device_response.status }}"
          New device response: "{{ ise_new_device_response.json }}"
