---
- name: Add Network Device to ISE
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Add Network Device to ISE
      cisco.ise.network_device:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        state: present
        name: "Switch-01"
        description: "Added via Ansible"
        NetworkDeviceIPList:
          - ipaddress: "192.168.10.5"
            mask: 32
        NetworkDeviceGroupList:
          - "Location#All Locations"
          - "Device Type#All Device Types"
        authenticationSettings:
          radiusSharedSecret: "YourSecureRadiusSecret123"
